=== xin81/Lingua/dictionary/permission/english_chinese.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:attribute name="src" type="xs:string" />
<!-- xs:attribute name="style" type="xs:string" -->
<xs:attribute name="name" type="xs:string" />
<xs:attribute name="id" type="xs:string" />

<xs:attribute name="style" default="simplified">
<xs:simpleType>
<xs:restriction base="xs:string">
 <xs:enumeration value="simplified" />
 <xs:enumeration value="traditional" />
</xs:restriction>
</xs:simpleType>
</xs:attribute>

<xs:complexType name="characterType">
<xs:simpleContent>
<xs:extension base="xs:string">
<xs:attribute ref="style" use="required" />
</xs:extension>
</xs:simpleContent>
</xs:complexType>

<xs:element name="pronunciation" type="xs:string" />
<xs:element name="characters" type="characterType" />

<xs:element name="gif">
<xs:complexType>
<xs:attribute ref="src" use="required" />
</xs:complexType>
</xs:element>

<xs:element name="audio">
<xs:complexType>
<xs:attribute ref="src" use="required" />
</xs:complexType>
</xs:element>

<xs:element name="dialect">
<xs:complexType>
<xs:sequence>
<xs:element ref="pronunciation" />
<xs:element ref="characters" />
</xs:sequence>
<xs:attribute name="name" default="mandarin">
<xs:simpleType>
<xs:restriction base="xs:string">
 <xs:enumeration value="mandarin" />
 <xs:enumeration value="cantonese" />
</xs:restriction>
</xs:simpleType>
</xs:attribute>
</xs:complexType>
</xs:element>

<xs:element name="source" />

<xs:element name="target">
<xs:complexType>
<xs:sequence>
<xs:element ref="dialect" maxOccurs="2" />
</xs:sequence>
<xs:attribute name="name" default="chinese">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:enumeration value="chinese" />
</xs:restriction>
</xs:simpleType>
</xs:attribute>
</xs:complexType>
</xs:element>

<xs:element name="url">
<xs:complexType>
<xs:sequence>
<xs:element ref="gif" maxOccurs="unbounded" />
<xs:element ref="audio" minOccurs="0" />
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="word">
<xs:complexType>
<xs:sequence>
<xs:element ref="source" />
<xs:element ref="target" />
<xs:element ref="url" />
</xs:sequence>
<xs:attribute ref="id" use="required" />
<xs:attribute ref="name" use="required" />
</xs:complexType>
</xs:element>

<xs:element name="dictionary">
<xs:complexType>
<xs:sequence>
<xs:element ref="word" maxOccurs="unbounded" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== xin81/Lingua/dictionary/permission/6479.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="6479" name="m&#243;">
<source name="english">imitate , copy</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>m&#243;</pronunciation>
<characters style="simplified">æ‘¹</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>m&#243;</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/6479.gif" />
<audio src="resources/audio/6479.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/7126.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="7126" name="ji&#257;o">
<source name="english">burnt , scorched , worried , anxious</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>ji&#257;o</pronunciation>
<characters style="simplified">ç„¦</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>ji&#257;o</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/7126.gif" />
<audio src="resources/audio/7126.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/6cbe.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="6cbe" name="zh&#257;n">
<source name="english">infected by , moisten , receive favors</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>zh&#257;n</pronunciation>
<characters style="simplified">æ²¾</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>zh&#257;n</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/6cbe.gif" />
<audio src="resources/audio/6cbe.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/7231.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="7231" name="&#224;i">
<source name="english">to love , affection , to be fond of , to like</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>&#224;i</pronunciation>
<characters style="simplified">爱</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>&#224;i</pronunciation>
<characters style="simplified">愛</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/7231.gif" />
<audio src="resources/audio/7231.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/82b1.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="82b1" name="hu&#257;">
<source name="english">flower , blossom , to spend (money, time) , fancy pattern</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>hu&#257;</pronunciation>
<characters style="simplified">èŠ±</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>hu&#257;</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/82b1.gif" />
<audio src="resources/audio/82b1.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/9e92.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="9e92" name="q&#237;">
<source name="english">mythical unicorn</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>q&#237;</pronunciation>
<characters style="simplified">éº’</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>q&#237;</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/9e92.gif" />
<audio src="resources/audio/9e92.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/6652.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="6652" name="sh&#224;i">
<source name="english">to sun</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>sh&#224;i</pronunciation>
<characters style="simplified">æ™’</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>sh&#224;i</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/6652.gif" />
<audio src="resources/audio/6652.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/6572.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="6572" name="qi&#257;o">
<source name="english">extort , knock , to strike , to knock (at a door) , to hit</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>qi&#257;o</pronunciation>
<characters style="simplified">æ•²</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>qi&#257;o</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/6572.gif" />
<audio src="resources/audio/6572.wav" />
</url>
</word>
</dictionary>
