=== xin81/Lingua/dictionary/permission/english_chinese.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:attribute name="src" type="xs:string" />
<!-- xs:attribute name="style" type="xs:string" -->
<xs:attribute name="name" type="xs:string" />
<xs:attribute name="id" type="xs:string" />

<xs:attribute name="style" default="simplified">
<xs:simpleType>
<xs:restriction base="xs:string">
 <xs:enumeration value="simplified" />
 <xs:enumeration value="traditional" />
</xs:restriction>
</xs:simpleType>
</xs:attribute>

<xs:complexType name="characterType">
<xs:simpleContent>
<xs:extension base="xs:string">
<xs:attribute ref="style" use="required" />
</xs:extension>
</xs:simpleContent>
</xs:complexType>

<xs:element name="pronunciation" type="xs:string" />
<xs:element name="characters" type="characterType" />

<xs:element name="gif">
<xs:complexType>
<xs:attribute ref="src" use="required" />
</xs:complexType>
</xs:element>

<xs:element name="audio">
<xs:complexType>
<xs:attribute ref="src" use="required" />
</xs:complexType>
</xs:element>

<xs:element name="dialect">
<xs:complexType>
<xs:sequence>
<xs:element ref="pronunciation" />
<xs:element ref="characters" />
</xs:sequence>
<xs:attribute name="name" default="mandarin">
<xs:simpleType>
<xs:restriction base="xs:string">
 <xs:enumeration value="mandarin" />
 <xs:enumeration value="cantonese" />
</xs:restriction>
</xs:simpleType>
</xs:attribute>
</xs:complexType>
</xs:element>

<xs:element name="source" />

<xs:element name="target">
<xs:complexType>
<xs:sequence>
<xs:element ref="dialect" maxOccurs="2" />
</xs:sequence>
<xs:attribute name="name" default="chinese">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:enumeration value="chinese" />
</xs:restriction>
</xs:simpleType>
</xs:attribute>
</xs:complexType>
</xs:element>

<xs:element name="url">
<xs:complexType>
<xs:sequence>
<xs:element ref="gif" maxOccurs="unbounded" />
<xs:element ref="audio" minOccurs="0" />
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="word">
<xs:complexType>
<xs:sequence>
<xs:element ref="source" />
<xs:element ref="target" />
<xs:element ref="url" />
</xs:sequence>
<xs:attribute ref="id" use="required" />
<xs:attribute ref="name" use="required" />
</xs:complexType>
</xs:element>

<xs:element name="dictionary">
<xs:complexType>
<xs:sequence>
<xs:element ref="word" maxOccurs="unbounded" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== xin81/Lingua/dictionary/permission/60e9.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="60e9" name="ch&#233;ng">
<source name="english">punish , discipline</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>ch&#233;ng</pronunciation>
<characters style="simplified">惩</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>ch&#233;ng</pronunciation>
<characters style="simplified">懲</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/60e9.gif" />
<audio src="resources/audio/60e9.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/72b6.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="72b6" name="zhu&#224;ng">
<source name="english">accusation , suit , state , condition , strong , great</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>zhu&#224;ng</pronunciation>
<characters style="simplified">状</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>zhu&#224;ng</pronunciation>
<characters style="simplified">狀</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/72b6.gif" />
<audio src="resources/audio/72b6.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/5fac.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="5fac" name="p&#225;ng">
<source name="english">irresolute</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>p&#225;ng</pronunciation>
<characters style="simplified">å¾¬</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>p&#225;ng</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/5fac.gif" />
<audio src="resources/audio/5fac.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/87fe.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="87fe" name="ch&#225;n">
<source name="english">moon , (striped) toad</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>ch&#225;n</pronunciation>
<characters style="simplified">èŸ¾</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>ch&#225;n</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/87fe.gif" />
<audio src="resources/audio/87fe.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/51b7.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="51b7" name="l&#283;ng">
<source name="english">cold</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>l&#283;ng</pronunciation>
<characters style="simplified">å†·</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>l&#283;ng</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/51b7.gif" />
<audio src="resources/audio/51b7.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/72f8.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="72f8" name="l&#237;">
<source name="english">(dog) , wild cat</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>l&#237;</pronunciation>
<characters style="simplified">ç‹¸</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>l&#237;</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/72f8.gif" />
<audio src="resources/audio/72f8.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/4e3b.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="4e3b" name="zh&#468;">
<source name="english">to own , to host , master , lord , primary</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>zh&#468;</pronunciation>
<characters style="simplified">ä¸»</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>zh&#468;</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/4e3b.gif" />
<audio src="resources/audio/4e3b.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/86b5.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="86b5" name="&#233;">
<source name="english">oyster</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>&#233;</pronunciation>
<characters style="simplified">èšµ</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>&#233;</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/86b5.gif" />
<audio src="resources/audio/86b5.wav" />
</url>
</word>
</dictionary>
