=== xin81/Lingua/dictionary/permission/english_chinese.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:attribute name="src" type="xs:string" />
<!-- xs:attribute name="style" type="xs:string" -->
<xs:attribute name="name" type="xs:string" />
<xs:attribute name="id" type="xs:string" />

<xs:attribute name="style" default="simplified">
<xs:simpleType>
<xs:restriction base="xs:string">
 <xs:enumeration value="simplified" />
 <xs:enumeration value="traditional" />
</xs:restriction>
</xs:simpleType>
</xs:attribute>

<xs:complexType name="characterType">
<xs:simpleContent>
<xs:extension base="xs:string">
<xs:attribute ref="style" use="required" />
</xs:extension>
</xs:simpleContent>
</xs:complexType>

<xs:element name="pronunciation" type="xs:string" />
<xs:element name="characters" type="characterType" />

<xs:element name="gif">
<xs:complexType>
<xs:attribute ref="src" use="required" />
</xs:complexType>
</xs:element>

<xs:element name="audio">
<xs:complexType>
<xs:attribute ref="src" use="required" />
</xs:complexType>
</xs:element>

<xs:element name="dialect">
<xs:complexType>
<xs:sequence>
<xs:element ref="pronunciation" />
<xs:element ref="characters" />
</xs:sequence>
<xs:attribute name="name" default="mandarin">
<xs:simpleType>
<xs:restriction base="xs:string">
 <xs:enumeration value="mandarin" />
 <xs:enumeration value="cantonese" />
</xs:restriction>
</xs:simpleType>
</xs:attribute>
</xs:complexType>
</xs:element>

<xs:element name="source" />

<xs:element name="target">
<xs:complexType>
<xs:sequence>
<xs:element ref="dialect" maxOccurs="2" />
</xs:sequence>
<xs:attribute name="name" default="chinese">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:enumeration value="chinese" />
</xs:restriction>
</xs:simpleType>
</xs:attribute>
</xs:complexType>
</xs:element>

<xs:element name="url">
<xs:complexType>
<xs:sequence>
<xs:element ref="gif" maxOccurs="unbounded" />
<xs:element ref="audio" minOccurs="0" />
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="word">
<xs:complexType>
<xs:sequence>
<xs:element ref="source" />
<xs:element ref="target" />
<xs:element ref="url" />
</xs:sequence>
<xs:attribute ref="id" use="required" />
<xs:attribute ref="name" use="required" />
</xs:complexType>
</xs:element>

<xs:element name="dictionary">
<xs:complexType>
<xs:sequence>
<xs:element ref="word" maxOccurs="unbounded" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== xin81/Lingua/dictionary/permission/9175.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="9175" name="ji&#224;o">
<source name="english">yeast</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>ji&#224;o</pronunciation>
<characters style="simplified">é…µ</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>ji&#224;o</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/9175.gif" />
<audio src="resources/audio/9175.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/8346.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="8346" name="j&#299;ng">
<source name="english">(surname) , thorns , brambles</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>j&#299;ng</pronunciation>
<characters style="simplified">荆</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>j&#299;ng</pronunciation>
<characters style="simplified">荊</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/8346.gif" />
<audio src="resources/audio/8346.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/8c1b.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="8c1b" name="d&#236;">
<source name="english">examine , truth (Buddhist)</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>d&#236;</pronunciation>
<characters style="simplified">ш░Ы</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>d&#236;</pronunciation>
<characters style="simplified">шлж</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/8c1b.gif" />
<audio src="resources/audio/8c1b.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/86b1.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="86b1" name="zh&#224;">
<source name="english">grasshopper</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>zh&#224;</pronunciation>
<characters style="simplified">èš±</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>zh&#224;</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/86b1.gif" />
<audio src="resources/audio/86b1.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/58c1.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="58c1" name="b&#236;">
<source name="english">wall , rampart</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>b&#236;</pronunciation>
<characters style="simplified">Â£Å</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>b&#236;</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/58c1.gif" />
<audio src="resources/audio/58c1.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/79df.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="79df" name="z&#363;">
<source name="english">rent , taxes</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>z&#363;</pronunciation>
<characters style="simplified">ç§Ÿ</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>z&#363;</pronunciation>
<characters style="simplified">same</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/79df.gif" />
<audio src="resources/audio/79df.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/6c22.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="6c22" name="q&#299;ng">
<source name="english">hydrogen</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>q&#299;ng</pronunciation>
<characters style="simplified">氢</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>q&#299;ng</pronunciation>
<characters style="simplified">氫</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/6c22.gif" />
<audio src="resources/audio/6c22.wav" />
</url>
</word>
</dictionary>

=== xin81/Lingua/dictionary/permission/8bda.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="english_chinese.xsd">

<word id="8bda" name="ch&#233;ng">
<source name="english">honest , sincere , true</source>
<target name="chinese">
<dialect name="mandarin">
<pronunciation>ch&#233;ng</pronunciation>
<characters style="simplified">诚</characters>
</dialect>

<!-- <dialect name="cantonese">
<pronunciation>ch&#233;ng</pronunciation>
<characters style="simplified">誠</characters>
</dialect> -->

</target>
<url>
<gif src="resources/img/8bda.gif" />
<audio src="resources/audio/8bda.wav" />
</url>
</word>
</dictionary>
